name: data_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  iconsax: ^0.0.8
  sqflite: ^2.3.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  path: ^1.8.3
  flutter_animate: ^4.5.0
  pdf: ^3.11.0
  path_provider: ^2.1.0
  printing: ^5.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


  fonts: 
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto_Condensed-Bold.ttf
        - asset: assets/fonts/Roboto_Condensed-Light.ttf
        - asset: assets/fonts/Roboto_Condensed-Regular.ttf
        - asset: assets/fonts/Roboto_Condensed-SemiBold.ttf


  assets:
    - assets/images/
    - assets/fonts/
